### PR TITLE
support new metric argument for nn2()

### LINKED ISSUE #3: Support other Minkowski metrics
The [ANN docs](http://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ANNmanual_1.1.pdf) suggest that the Euclidean metric is used by default. Some digging in [the code](https://github.com/jefferis/RANN/blob/master/src/ANN/ANN.h#L336) and in above docs suggest that this is also true for `RANN`.

According to Section 2.2.1 (p. 14 ff.), only the macros in the code linked above need to be redefined to use other Minkowski norms. To define a code base where Manhattan, Euclidean and "max" metric are simultaneously accessible, this probably needs to be replaced by a template parameter that defines the implementation of the four operators.

The purpose is to accelerate statistical matching using the Gower distance: I think I can transform a "Gower distance problem" to a "Manhattan distance problem" but then `RANN` should be able to solve it (it is called by the `StatMatch` package).

Does this make sense to you?

### PR DESCRIPTION
**Pull request by krlmlr**
- calls are forwarded to `RANN1`
- documentation in the main README file

Fixes #3.

Closes #4 (=contains it).

### CODE REVIEW

**Comment by krlmlr** [comment]
Now, `get_nn2_func` uses an environment for lookup, the median run time jumps around 10 microseconds per call.

```
> microbenchmark(RANN:::get_nn2_func("manhattan"), times = 100000)
Unit: microseconds
                             expr   min    lq     mean median     uq      max neval
 RANN:::get_nn2_func("manhattan") 4.771 6.067 10.57319  7.057 14.842 1706.912 1e+05
```

**Comment by jefferis** [comment]
The use of the environment is a nice way to speed things up. My only comment now would be: should we just bypass worker_nn2 for Euclidean distance? That way the implementation is essentially unchanged for the standard Euclidean distance.

**Comment by krlmlr** [comment]
For a long-term solution, I think it's best if the `master` and `master-L1` branches are as similar as possible. I'll find a solution with minimal penalty for the "default" case.

**Comment by jefferis** [comment]
So the conclusion for the time being is that we simply refer to your new RANN1 package in the docs as implemented in your #10. This PR has therefore been superseded so I am closing it (even though some of the approaches you tried here were interesting).

**Comment by krlmlr** [comment]
Fine with me, thanks.

**Pull request closed without merging**
