### PR TITLE
Update to match CRAN version

### PR DESCRIPTION
**Pull request by krlmlr**
http://cran.r-project.org/web/packages/RANN.L1/

### CODE REVIEW

**Comment by jefferis** [comment]
Looks good to me. Thanks. NB travis failure is due to CRAN version check – maybe we should disable this. Or bump the version for development.

**Comment by krlmlr** [comment]
Right, I forgot this. The version checks are useful, because they also include the now mandatory spell check. Some use a version like 2.5.0.9000 to indicate a development version, but we could simply use 2.5.0 (which is different to 2.5):

```
> compareVersion("2.5", "2.5.0")
[1] -1
```

**Comment by jefferis** [comment]
> but we could simply use 2.5.0 (which is different to 2.5):

thanks – that sounds fine.

**Comment by krlmlr** [comment]
If you could just make the change to the `master` branch, I can merge from there (to keep the master -> master-L1 flow).

**Pull request merged**
